# Generated by Django 4.2.1 on 2023-06-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset_Tracker', '0002_asset_assettype_assetimage_asset_asset_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetimage',
            name='image',
            field=models.ImageField(upload_to='media/asset_images/'),
        ),
    ]
